name: Main

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['6.x', '7.x', '8.x']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: dotnet build --configuration Release
